"""Tests for the media adapters: Tesseract OCR and OpenCV forensics.

OCR is exercised against a fully fake ``pytesseract`` module (no binary
required); forensics runs against a real in-memory image so the OpenCV
pipeline is genuinely exercised.
"""

import sys
import types
from typing import Any

import numpy as np
import pytest
from app.application.ports.media import (
    ForensicsReport,
    MediaProcessingError,
    OcrResult,
)
from app.core.exceptions import ConfigurationError
from app.infrastructure.media.mock_media_adapters import (
    MockForensicsAdapter,
    MockOcrAdapter,
)
from app.infrastructure.media.opencv_forensics import OpenCvForensicsAdapter
from app.infrastructure.media.pytesseract_ocr import TesseractOcrAdapter
from app.infrastructure.media.utils import decode_image

# ----------------------------------------------------------------------
# Fake pytesseract module
# ----------------------------------------------------------------------


def make_fake_pytesseract(
    *,
    text: list[str] | None = None,
    conf: list[str] | None = None,
    missing_binary: bool = False,
) -> types.ModuleType:
    """Build a stand-in ``pytesseract`` module with configurable behavior.

    Args:
        text: Per-cell text values returned by ``image_to_data``.
        conf: Per-cell confidence values ("-1" means no text).
        missing_binary: If True, ``get_tesseract_version`` raises the
            not-found error the adapter must translate.
    """
    fake = types.ModuleType("pytesseract")
    fake.TesseractNotFoundError = type("TesseractNotFoundError", (RuntimeError,), {})

    if missing_binary:

        def get_version() -> None:
            raise fake.TesseractNotFoundError("binary missing")

    else:
        get_version = lambda: types.SimpleNamespace(  # noqa: E731
            __str__=lambda self: "5.4.0"
        )

    class Output:
        DICT = 3

    fake.Output = Output

    def image_to_data(image: Any, lang: str, output_type: Any) -> dict[str, list[str]]:
        return {"text": text or [], "conf": conf or []}

    fake.get_tesseract_version = get_version
    fake.image_to_data = image_to_data
    return fake


@pytest.fixture()
def fake_pytesseract(monkeypatch: pytest.MonkeyPatch) -> types.ModuleType:
    """Inject the fake pytesseract module for the whole test module."""
    fake = make_fake_pytesseract()
    monkeypatch.setitem(sys.modules, "pytesseract", fake)
    return fake


# ----------------------------------------------------------------------
# Tesseract OCR adapter
# ----------------------------------------------------------------------


def test_ocr_extracts_text_and_confidence(
    fake_pytesseract: types.ModuleType,
    real_png_bytes: bytes,
) -> None:
    """Words with real confidence must join into text with a mean score."""
    fake_pytesseract.image_to_data = lambda image, lang, output_type: {
        "text": ["Hello", "", "world", "unreadable"],
        "conf": ["95", "-1", "80", "-1"],
    }
    adapter = TesseractOcrAdapter(languages="eng")
    result = adapter.extract_text(real_png_bytes)
    assert result.text == "Hello world"
    assert result.confidence == pytest.approx(87.5)
    assert result.language == "eng"


def test_ocr_empty_text_yields_none_confidence(
    fake_pytesseract: types.ModuleType,
    real_png_bytes: bytes,
) -> None:
    """No recognizable text must yield an empty string and None confidence."""
    adapter = TesseractOcrAdapter()
    result = adapter.extract_text(real_png_bytes)
    assert result == OcrResult(text="", confidence=None, language="eng")


def test_ocr_missing_binary_raises_configuration_error(monkeypatch: pytest.MonkeyPatch) -> None:
    """A missing tesseract binary must surface as ConfigurationError."""
    monkeypatch.setitem(sys.modules, "pytesseract", make_fake_pytesseract(missing_binary=True))
    with pytest.raises(ConfigurationError, match="tesseract binary not found"):
        TesseractOcrAdapter()


# ----------------------------------------------------------------------
# OpenCV forensics adapter (real images)
# ----------------------------------------------------------------------


@pytest.fixture()
def real_png_bytes() -> bytes:
    """A real 64x48 PNG generated by OpenCV itself."""
    image = np.full((48, 64, 3), 128, dtype=np.uint8)
    ok, buffer = cv2_imencode_png(image)
    assert ok
    return buffer.tobytes()


def cv2_imencode_png(image: np.ndarray) -> tuple[bool, np.ndarray]:
    """Encode an image to PNG via OpenCV (imported lazily)."""
    import cv2

    return cv2.imencode(".png", image)


def test_forensics_reports_dimensions_and_low_risk(real_png_bytes: bytes) -> None:
    """A clean synthetic image must report its size and low tamper risk."""
    report = OpenCvForensicsAdapter().analyze(real_png_bytes)
    assert isinstance(report, ForensicsReport)
    assert report.signals["width"] == 64
    assert report.signals["height"] == 48
    assert report.signals["reencode_signal"] == "low"
    assert 0.0 <= report.risk_score <= 1.0


def test_forensics_risk_is_bounded(real_png_bytes: bytes) -> None:
    """Risk score must stay within [0, 1] regardless of image content."""
    report = OpenCvForensicsAdapter().analyze(real_png_bytes)
    assert 0.0 <= report.risk_score <= 1.0


def test_decode_image_rejects_garbage_bytes() -> None:
    """Undecodable bytes must raise MediaProcessingError."""
    with pytest.raises(MediaProcessingError, match="cannot decode"):
        decode_image(b"this is not an image")


def test_forensics_rejects_garbage_bytes() -> None:
    """The adapter must surface decode failures as MediaProcessingError."""
    with pytest.raises(MediaProcessingError, match="cannot decode"):
        OpenCvForensicsAdapter().analyze(b"garbage" * 100)


# ----------------------------------------------------------------------
# Mocks
# ----------------------------------------------------------------------


def test_mock_ocr_counts_calls_and_returns_fixed_result() -> None:
    """The OCR mock must count calls and return its fixed result."""
    adapter = MockOcrAdapter()
    result = adapter.extract_text(b"image")
    assert result.text == "mock ocr text"
    assert result.confidence == 0.9
    assert adapter.calls == 1
    adapter.extract_text(b"another")
    assert adapter.calls == 2


def test_mock_forensics_counts_calls() -> None:
    """The forensics mock must count calls and return a fixed report."""
    adapter = MockForensicsAdapter()
    report = adapter.analyze(b"image")
    assert report.risk_score == 0.0
    assert report.signals == {"mock": True}
    adapter.analyze(b"image")
    assert adapter.calls == 2
